pipeline:
  # Fetch folders from distributed cache
  sftp_cache_restore:
    image: plugins/sftp-cache
    restore: true
    mount:
      - /drone/.ivy2
      - /drone/.coursier-cache
      - /drone/.sbt
      - /drone/.git
    when:
      event: [push, pull_request, tag, deployment]

  tests:
    image: scalaplatform/scala:0.6
    commands:
      - git fetch --tags && git log | head -n 20
      - sbt -Dfile.encoding=UTF-8 -J-XX:ReservedCodeCacheSize=256M -J-Xmx3046M -J-Xms3046M -J-server zincRoot/test:compile scalafmtCheck "$CI_PUBLISH_BRIDGES" crossTestBridges zincRoot/test zincRoot/scripted

  # Save folders in distributed cache
  sftp_cache_rebuild:
    image: plugins/sftp-cache
    rebuild: true
    mount:
      - /drone/.ivy2
      - /drone/.coursier-cache
      - /drone/.sbt
      - /drone/.git
    when:
      event: [push, pull_request, tag, deployment]

matrix:
  include:
    - CI_PUBLISH_BRIDGES: publishBridges 2.11.11
    - CI_PUBLISH_BRIDGES: publishBridges 2.12.2
