language: scala

before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

scala:
  - 2.11.8
  - 2.12.1

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

env:
  matrix:
    - SBT_CMD="zincScripted/test zinc/test zincPersist/test zincIvyIntegration/test zincTesting/test scalafmtCheck"
    - SBT_CMD="compilerInterface/test zincCompile/test zincCompileCore/test zincClasspath/test zincApiInfo/test zincClassfile/test scalafmtCheck"
    - SBT_CMD="zincRoot/scripted zincCore/test zincBenchmarks/test scalafmtCheck"
    - SBT_CMD="crossTestBridges scalafmtCheck"

script:
  - sbt -Dfile.encoding=UTF8 -J-XX:ReservedCodeCacheSize=256M "publishBridges $TRAVIS_SCALA_VERSION" $SBT_CMD

jdk:
  - oraclejdk8
