# Use Docker-based container (instead of OpenVZ)
sudo: false

language: scala

matrix:
  fast_finish: true

before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

scala:
  - 2.11.11
  - 2.12.2

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

env:
  matrix:
    - SBT_CMD="zincTesting/test zincCompileCore/test zincCore/test zincPersist/test zincIvyIntegration/test zincBenchmarks/test zincCompile/test zinc/test scalafmtCheck"
    - SBT_CMD="zincScripted/test zincRoot/scripted scalafmtCheck"
    - SBT_CMD="compilerInterface/test zincClassfile/test zincApiInfo/test crossTestBridges scalafmtCheck"

script:
  - sbt -Dfile.encoding=UTF8 -J-XX:ReservedCodeCacheSize=256M -J-Xmx2048M -J-Xms2048M -J-server "publishBridges $TRAVIS_SCALA_VERSION" $SBT_CMD

jdk:
  - oraclejdk8
